{% set name = "cloud-data-connector" %}
{% set version = "1.0.3" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/cloud_data_connector-{{ version }}.tar.gz
  sha256: d077bc4cc034cb0ff19eab7968de19cbbbdb62eea6387b41664645a6c05fc156

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  number: 2

requirements:
  host:
    - python {{ python_min }}
    - setuptools >=61.0
    - setuptools-scm
    - pip
  run:
    - python >={{ python_min }},<3.11
    - azureml >=0.2.7
    - azure-ai-ml >=1.4.0
    - azure-identity >=1.12.0
    - azure-storage-blob >=1.4.1
    - azure-core >=1.26.3
    - boto3 >=1.26.154
    - google-api-core >=2.0.0
    - google-auth >=1.33.0
    - google-auth-oauthlib >=0.4.1
    - google-cloud-bigquery >=3.11.4
    - google-cloud-storage >=2.1.0
    - packaging >=21.3
    - python-dotenv >=1.0.0
    - moto >=5.0.0

test:
  requires:
    - python {{ python_min }}
  imports:
    - cloud_data_connector

about:
  home: https://github.com/IntelAI/models
  summary: 'Data connector is a tool to connect to AzureML, Azure blob, GCP storage, GCP Big Query and AWS storage S3. The goal is provide all cloud managers in one place and provide documentation for an easy integration.'
  license: Apache-2.0
  license_file: LICENSE

extra:
  recipe-maintainers:
    - jesushl
    - aagalleg
    - fleza
    - ma-pineda
    - gerardod
